// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAo7yQ4L3adgC1AnkiGk1gi7SLdB41JafM',
    appId: '1:129072746078:web:5acefe4dc100409f176ecf',
    messagingSenderId: '129072746078',
    projectId: 'spendwise-52bf8',
    authDomain: 'spendwise-52bf8.firebaseapp.com',
    storageBucket: 'spendwise-52bf8.firebasestorage.app',
    measurementId: 'G-4X07CP17MY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDB8pbAE61rf2VqiN-BsFZvxtlP9f4E3xc',
    appId: '1:129072746078:android:2e81c1b81d6888af176ecf',
    messagingSenderId: '129072746078',
    projectId: 'spendwise-52bf8',
    storageBucket: 'spendwise-52bf8.firebasestorage.app',
  );
}
